# Generated by Django 4.2.7 on 2023-11-02 12:48

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('last_update_time', models.TimeField(verbose_name='Last update instance time')),
                ('creation_time', models.TimeField(verbose_name='Last update instance time')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('last_update_time', models.TimeField(verbose_name='Last update instance time')),
                ('creation_time', models.TimeField(verbose_name='Last update instance time')),
                ('year', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('last_update_time', models.TimeField(verbose_name='Last update instance time')),
                ('creation_time', models.TimeField(verbose_name='Last update instance time')),
                ('dealer_name', models.CharField(max_length=255, verbose_name='Car dealer name')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('balance', models.FloatField(default=0, verbose_name='Car Dealer balance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('last_update_time', models.TimeField(verbose_name='Last update instance time')),
                ('creation_time', models.TimeField(verbose_name='Last update instance time')),
                ('client_name', models.CharField(max_length=255)),
                ('client_second_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255)),
                ('registration_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('last_update_time', models.TimeField(verbose_name='Last update instance time')),
                ('creation_time', models.TimeField(verbose_name='Last update instance time')),
                ('supplier_name', models.CharField(max_length=255)),
                ('year_of_origin', models.PositiveIntegerField(max_length=4)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierSalesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('last_update_time', models.TimeField(verbose_name='Last update instance time')),
                ('creation_time', models.TimeField(verbose_name='Last update instance time')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(max_length=100, verbose_name='Count')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDealers.car', verbose_name='Car')),
                ('car_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDealers.cardealer', verbose_name='Car Dealer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDealers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Sales History',
                'verbose_name_plural': 'Supplier Sales Histories',
            },
        ),
        migrations.CreateModel(
            name='SupplierPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('last_update_time', models.TimeField(verbose_name='Last update instance time')),
                ('creation_time', models.TimeField(verbose_name='Last update instance time')),
                ('name', models.CharField(max_length=255, verbose_name='Promotion name')),
                ('description', models.TextField(verbose_name='Promotion Description')),
                ('start_date', models.DateField(verbose_name='Promotion start date')),
                ('end_date', models.DateField(verbose_name='Promotion end date')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Promotion percent')),
                ('car_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDealers.cardealer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDealers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Promotion',
                'verbose_name_plural': 'Supplier Promotions',
            },
        ),
        migrations.CreateModel(
            name='SalesDealerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('last_update_time', models.TimeField(verbose_name='Last update instance time')),
                ('creation_time', models.TimeField(verbose_name='Last update instance time')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(max_length=100, verbose_name='Count')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDealers.car', verbose_name='Car')),
                ('car_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDealers.cardealer', verbose_name='Car Dealer')),
            ],
            options={
                'verbose_name': 'Sales Dealer History',
                'verbose_name_plural': 'Sales Dealer Histories',
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('last_update_time', models.TimeField(verbose_name='Last update instance time')),
                ('creation_time', models.TimeField(verbose_name='Last update instance time')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(max_length=100, verbose_name='Count')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDealers.car', verbose_name='Car')),
                ('car_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDealers.cardealer', verbose_name='Car Dealer')),
            ],
            options={
                'verbose_name': 'Purchase History',
                'verbose_name_plural': 'Purchase Histories',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('last_update_time', models.TimeField(verbose_name='Last update instance time')),
                ('creation_time', models.TimeField(verbose_name='Last update instance time')),
                ('name', models.CharField(max_length=255)),
                ('horse_power_count', models.PositiveIntegerField()),
                ('color', models.CharField(choices=[('Red', 'RED'), ('Blue', 'BLUE'), ('Green', 'GREEN'), ('Yellow', 'YELLOW'), ('White', 'WHITE'), ('Black', 'BLACK'), ('Silver', 'SILVER'), ('Gray', 'GRAY')], default='White', max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDealers.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarDealerPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('last_update_time', models.TimeField(verbose_name='Last update instance time')),
                ('creation_time', models.TimeField(verbose_name='Last update instance time')),
                ('name', models.CharField(max_length=255, verbose_name='Promotion name')),
                ('description', models.TextField(verbose_name='Promotion Description')),
                ('start_date', models.DateField(verbose_name='Promotion start date')),
                ('end_date', models.DateField(verbose_name='Promotion end date')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Promotion percent')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDealers.car', verbose_name='Car')),
                ('car_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDealers.cardealer')),
            ],
            options={
                'verbose_name': 'Car Dealer Promotion',
                'verbose_name_plural': 'Car Dealer Promotions',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDealers.model'),
        ),
        migrations.CreateModel(
            name='ClientCarDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('last_update_time', models.TimeField(verbose_name='Last update instance time')),
                ('creation_time', models.TimeField(verbose_name='Last update instance time')),
                ('car_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDealers.cardealer')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDealers.client')),
            ],
            options={
                'unique_together': {('client', 'car_dealer')},
            },
        ),
        migrations.CreateModel(
            name='CarSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('last_update_time', models.TimeField(verbose_name='Last update instance time')),
                ('creation_time', models.TimeField(verbose_name='Last update instance time')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDealers.car')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDealers.supplier')),
            ],
            options={
                'unique_together': {('car', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='CarDealerSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('last_update_time', models.TimeField(verbose_name='Last update instance time')),
                ('creation_time', models.TimeField(verbose_name='Last update instance time')),
                ('car_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDealers.cardealer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carDealers.supplier')),
            ],
            options={
                'unique_together': {('car_dealer', 'supplier')},
            },
        ),
    ]
