# Generated by Django 4.2.7 on 2023-11-04 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('create_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('create_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('name', models.CharField(max_length=255)),
                ('horse_power_count', models.PositiveIntegerField()),
                ('color', models.CharField(choices=[('Red', 'RED'), ('Blue', 'BLUE'), ('Green', 'GREEN'), ('Yellow', 'YELLOW'), ('White', 'WHITE'), ('Black', 'BLACK'), ('Silver', 'SILVER'), ('Gray', 'GRAY')], default='White', max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('create_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('year', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.model')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('create_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.car')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplier')),
            ],
            options={
                'unique_together': {('car', 'supplier')},
            },
        ),
    ]
