# Generated by Django 4.2.7 on 2023-11-08 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Car', '0001_initial'),
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplier'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.model'),
        ),
        migrations.AlterUniqueTogether(
            name='carsupplier',
            unique_together={('car', 'supplier')},
        ),
    ]
