# Generated by Django 4.2.8 on 2024-01-03 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CarDealer', '0001_initial'),
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardealercar',
            name='car_dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealer.cardealer'),
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('brand', 'model', 'horse_power_count', 'year', 'color')},
        ),
        migrations.AlterUniqueTogether(
            name='cardealercar',
            unique_together={('car', 'car_dealer')},
        ),
    ]
