# Generated by Django 4.2.7 on 2023-11-11 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Car', '0001_initial'),
        ('Supplier', '0001_initial'),
        ('CarDealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplier'),
        ),
        migrations.AddField(
            model_name='cardealercar',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.car'),
        ),
        migrations.AddField(
            model_name='cardealercar',
            name='car_dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealer.cardealer'),
        ),
        migrations.AlterUniqueTogether(
            name='carsupplier',
            unique_together={('car', 'supplier')},
        ),
        migrations.AlterUniqueTogether(
            name='cardealercar',
            unique_together={('car', 'car_dealer')},
        ),
    ]
