# Generated by Django 4.2.7 on 2023-11-11 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('brand', 'model', 'horse_power_count', 'year', 'color')},
        ),
    ]
