# Generated by Django 4.2.7 on 2023-11-24 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0004_alter_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='horse_power_count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(default=2023, validators=[django.core.validators.MaxValueValidator(2024)]),
        ),
        migrations.AlterField(
            model_name='cardealercar',
            name='count',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
