# Generated by Django 4.2.8 on 2024-01-03 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0005_alter_car_horse_power_count_alter_car_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(default=2024, validators=[django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
