# Generated by Django 4.2.7 on 2023-11-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0002_alter_brand_create_time_alter_brand_update_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='color',
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Red', 'RED'), ('Blue', 'BLUE'), ('Green', 'GREEN'), ('Yellow', 'YELLOW'), ('White', 'WHITE'), ('Black', 'BLACK'), ('Silver', 'SILVER'), ('Gray', 'GRAY')], default='White', max_length=10),
        ),
    ]
