# Generated by Django 4.2.7 on 2023-11-04 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Supplier', '0001_initial'),
        ('Car', '0001_initial'),
        ('CarDealer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierSalesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('create_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(verbose_name='Count')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.car', verbose_name='Car')),
                ('car_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealer.cardealer', verbose_name='Car Dealer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Sales History',
                'verbose_name_plural': 'Supplier Sales Histories',
            },
        ),
        migrations.CreateModel(
            name='SalesDealerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('create_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(verbose_name='Count')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.car', verbose_name='Car')),
                ('car_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealer.cardealer', verbose_name='Car Dealer')),
            ],
            options={
                'verbose_name': 'Sales Dealer History',
                'verbose_name_plural': 'Sales Dealer Histories',
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('create_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(verbose_name='Count')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.car', verbose_name='Car')),
                ('car_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealer.cardealer', verbose_name='Car Dealer')),
            ],
            options={
                'verbose_name': 'Purchase History',
                'verbose_name_plural': 'Purchase Histories',
            },
        ),
    ]
