# Generated by Django 4.2.8 on 2024-01-03 11:05

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('dealer_name', models.CharField(max_length=255, unique=True, verbose_name='Car dealer name')),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('balance', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Car Dealer balance')),
                ('specification', models.JSONField(blank=True, default=None, null=True)),
                ('cars', models.ManyToManyField(through='Car.CarDealerCar', to='Car.car')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
