# Generated by Django 4.2.7 on 2023-11-11 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CarDealer', '0001_initial'),
        ('Supplier', '0001_initial'),
        ('Car', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardealersupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplier'),
        ),
        migrations.AddField(
            model_name='cardealer',
            name='cars',
            field=models.ManyToManyField(through='Car.CarDealerCar', to='Car.car'),
        ),
    ]
