# Generated by Django 4.2.8 on 2024-01-03 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarDealer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardealer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
