# Generated by Django 4.2.7 on 2023-11-09 12:23

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarDealer', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardealer',
            name='specification',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
