# Generated by Django 4.2.7 on 2023-11-04 18:44

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('create_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('dealer_name', models.CharField(max_length=255, verbose_name='Car dealer name')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('balance', models.FloatField(default=0, verbose_name='Car Dealer balance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarDealerSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('create_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('car_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealer.cardealer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplier')),
            ],
            options={
                'unique_together': {('car_dealer', 'supplier')},
            },
        ),
    ]
