FROM python:3.9.0


RUN mkdir -p /usr/src/app/
RUN mkdir -p /usr/src/app/static/

WORKDIR /usr/src/app/

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

COPY requirements.txt .
COPY . /usr/src/app/

RUN pip install -r requirements.txt

COPY ./entrypoint.sh /
ENTRYPOINT ["sh", "./entrypoint.sh"]