# Generated by Django 4.2.8 on 2024-01-03 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Supplier', '0001_initial'),
        ('Discount', '0001_initial'),
        ('CarDealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdiscount',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplier'),
        ),
        migrations.AddField(
            model_name='cardealerdiscount',
            name='car_dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealer.cardealer'),
        ),
    ]
