# Generated by Django 4.2.8 on 2024-01-09 07:45

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discount', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardealerdiscount',
            name='params',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='supplierdiscount',
            name='params',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
