# Generated by Django 4.2.7 on 2023-11-04 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Supplier', '0001_initial'),
        ('Car', '0001_initial'),
        ('CarDealer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('create_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('name', models.CharField(max_length=255, verbose_name='Promotion name')),
                ('description', models.TextField(blank=True, verbose_name='Promotion Description')),
                ('start_date', models.DateTimeField(verbose_name='Promotion start date')),
                ('end_date', models.DateTimeField(verbose_name='Promotion end date')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Promotion percent')),
                ('car_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealer.cardealer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Promotion',
                'verbose_name_plural': 'Supplier Promotions',
            },
        ),
        migrations.CreateModel(
            name='CarDealerPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('create_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('name', models.CharField(max_length=255, verbose_name='Promotion name')),
                ('description', models.TextField(blank=True, verbose_name='Promotion Description')),
                ('start_date', models.DateTimeField(verbose_name='Promotion start date')),
                ('end_date', models.DateTimeField(verbose_name='Promotion end date')),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Promotion percent')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.car', verbose_name='Car')),
                ('car_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealer.cardealer')),
            ],
            options={
                'verbose_name': 'Car Dealer Promotion',
                'verbose_name_plural': 'Car Dealer Promotions',
            },
        ),
    ]
