# Generated by Django 4.2.7 on 2023-11-04 18:44

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('create_time', models.DateTimeField(default='15.05.2023 09:30')),
                ('supplier_name', models.CharField(max_length=255)),
                ('year_of_origin', models.PositiveIntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'ordering': ['supplier_name'],
            },
        ),
    ]
