# Generated by Django 4.2.7 on 2023-11-08 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_client_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Client balance'),
        ),
    ]
