# Generated by Django 4.2.8 on 2024-01-03 11:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Car', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('supplier_name', models.CharField(max_length=255, unique=True)),
                ('year_of_origin', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1700), django.core.validators.MaxValueValidator(2024)])),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'ordering': ['supplier_name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('price_with_discount', models.DecimalField(decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.car')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supplier.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='supplier',
            name='cars',
            field=models.ManyToManyField(through='Supplier.SupplierCars', to='Car.car'),
        ),
    ]
