# Generated by Django 4.2.7 on 2023-11-11 07:08

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('supplier_name', models.CharField(max_length=255, unique=True)),
                ('year_of_origin', models.PositiveIntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('cars', models.ManyToManyField(through='Car.CarSupplier', to='Car.car')),
            ],
            options={
                'ordering': ['supplier_name'],
            },
        ),
    ]
