# Generated by Django 4.2.7 on 2023-11-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_remove_car_price_carsupplier_price_and_more'),
        ('Supplier', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='cars',
            field=models.ManyToManyField(through='Car.CarSupplier', to='Car.car'),
        ),
    ]
