# Generated by Django 4.2.7 on 2023-11-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='year_of_origin',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
