# Generated by Django 4.2.7 on 2023-11-24 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0003_alter_supplier_year_of_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='year_of_origin',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1700), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
