# Generated by Django 4.2.8 on 2024-01-03 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supplier', '0004_alter_supplier_year_of_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='year_of_origin',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1700), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
