# Generated by Django 4.2.8 on 2024-01-03 11:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CarDealer', '0001_initial'),
        ('Car', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDealerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(verbose_name='Count')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'verbose_name': 'Sales Dealer History',
                'verbose_name_plural': 'Sales Dealer Histories',
            },
        ),
        migrations.CreateModel(
            name='SupplierSalesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(verbose_name='Count')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.car', verbose_name='Car')),
                ('car_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDealer.cardealer', verbose_name='Car Dealer')),
            ],
            options={
                'verbose_name': 'Supplier Sales History',
                'verbose_name_plural': 'Supplier Sales Histories',
            },
        ),
    ]
