# Generated by Django 4.2.7 on 2023-11-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salesdealerhistory',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salesdealerhistory',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='suppliersaleshistory',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='suppliersaleshistory',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
