# Generated by Django 4.2.8 on 2024-01-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdealerhistory',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='suppliersaleshistory',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
