# Generated by Django 4.2.8 on 2024-01-09 08:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_initial'),
        ('History', '0003_alter_salesdealerhistory_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdealerhistory',
            name='client',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Client.client'),
            preserve_default=False,
        ),
    ]
