# Generated by Django 4.2.7 on 2023-11-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0003_purchasehistory_price_salesdealerhistory_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseHistory',
        ),
    ]
